### ISSUE TITLE
(Desktop) 상품 상세 페이지

### ISSUE THREAD

**Issue by LeeMir** [Wallet-expedition/MODIMOA#123]
## 개요(리팩토링이 왜 필요한 지)

![image](https://user-images.githubusercontent.com/42960217/158115308-019ba20a-6b9a-4ab5-95ba-1b0e9db5ddff.png)

- 창 높이를 늘리니까 뭔가 어색함

## TODO List

- [ ] 검색 바 밑에 여유 공간(margin이나 padding) 주기
- [ ] 하단 장바구니 담기 가운데 정렬
- [ ] 뒤로 가기(리스트로 돌아가기) 버튼 있어야 할 듯
